# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.ci for CI config

ci:
  autoupdate_schedule: monthly
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: check-future-annotations
        name: check future annotations
        language: script
        entry: scripts/check-future-annotations.sh
        types: [python]
        exclude: ^docs/source/
      - id: check-license-header
        name: check license header
        language: script
        entry: scripts/check-license-header.sh
        types_or: [cython, python]
        exclude: ^docs/source/
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.1.9
    hooks:
      - id: ruff
  - repo: 'https://github.com/psf/black'
    rev: 23.12.1
    hooks:
      - id: black
        types: [python]
  - repo: 'https://github.com/MarcoGorelli/cython-lint'
    rev: v0.16.0
    hooks:
      - id: cython-lint
  - repo: 'https://github.com/pycqa/flake8'
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-force
          - flake8-pytest-style
        types_or: [cython, python]
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.13.2
    hooks:
      - id: isort
        types_or: [cython, python]
  - repo: 'https://github.com/PyCQA/pylint'
    rev: v3.0.3
    hooks:
      - id: pylint
        additional_dependencies:
          - pylint-per-file-ignores
        args:
          - '-rn'
          - '--fail-under=9'
          - '--disable=no-name-in-module'
          - '--disable=import-error'
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        types_or: [cython, python]
        args:
          - '--py38-plus'
          - '--keep-runtime-typing'
  - repo: 'https://github.com/abravalheri/validate-pyproject'
    rev: v0.15
    hooks:
      - id: validate-pyproject
