name: docs

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: "${{ github.workspace }}/.local"
      BACKEND_VERSION: "2.28.0"
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - uses: actions/checkout@v3

      - name: Cache backend
        id: cache-backend
        uses: actions/cache@v3
        with:
          path: ${{ env.BACKEND_DIR }}
          key: ${{ runner.os }}-${{ env.BACKEND_VERSION }}-backend

      - name: Install backend
        if: steps.cache-backend.outputs.cache-hit != 'true'
        run: |
          ./scripts/download-mbedtls.sh $BACKEND_VERSION $BACKEND_DIR/src
          ./scripts/install-mbedtls.sh $BACKEND_DIR/src $BACKEND_DIR

      - name: Install library
        env:
          C_INCLUDE_PATH: "${{ env.BACKEND_DIR }}/include"
          LIBRARY_PATH: "${{ env.BACKEND_DIR }}/lib"
        run: python setup.py build_ext --inplace

      - name: Install deps
        run: >
          python -m pip install
          -r requirements.txt
          -r requirements/build.txt
          -r requirements/docs.txt

      - name: Build docs
        run: |
          ln -s "${{ env.BACKEND_DIR }}/lib/libmbed*so" docs
          make -C docs html

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/build/html/
          if-no-files-found: error
