name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: "${{ github.workspace }}/.local"
      BACKEND_VERSION: "2.28.0"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build backend
        run: |
          ./scripts/download-mbedtls.sh $BACKEND_VERSION $BACKEND_DIR/src
          ./scripts/install-mbedtls.sh $BACKEND_DIR/src $BACKEND_DIR
          ln -s "${{ env.BACKEND_DIR }}/lib/libmbed*so" docs

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements/build.txt

      - name: Install deps
        run: >
          python -m pip install
          -r requirements.txt
          -r requirements/build.txt

      - name: Build library
        env:
          C_INCLUDE_PATH: "${{ env.BACKEND_DIR }}/include"
          LIBRARY_PATH: "${{ env.BACKEND_DIR }}/lib"
        run: python setup.py build_ext --inplace

      - name: Build and commit
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: docs/source
          requirements_path: requirements/docs.txt

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
