name: lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install linters
        run: python -m pip install -r requirements/lint.txt

      - name: Check imports
        run: find src tests -name '*.py' | xargs python -m isort --check --diff
        if: always()

      - name: Check format
        run: find src tests -name '*.py' | xargs python -m black --check --diff
        if: always()
