name: typing

on: [push, pull_request]

jobs:
  run-type-checkers:
    name: Run type checkers
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: "${{ github.workspace }}/.local"
      BACKEND_VERSION: "2.28.0"
    steps:
      - uses: actions/checkout@v3

      - name: Cache backend
        id: cache-backend
        uses: actions/cache@v3
        with:
          path: ${{ env.BACKEND_DIR }}
          key: ${{ runner.os }}-${{ env.GITHUB_REF_NAME }}-${{ env.BACKEND_VERSION }}-v1

      - name: Build backend
        if: steps.cache-backend.outputs.cache-hit != 'true'
        run: |
          ./scripts/download-mbedtls.sh $BACKEND_VERSION $BACKEND_DIR/src
          ./scripts/install-mbedtls.sh $BACKEND_DIR/src $BACKEND_DIR

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements/lint.txt

      - name: Install deps
        run: >
          python -m pip install
          -r requirements.txt
          -r requirements/lint.txt

      - name: Build and install
        env:
          C_INCLUDE_PATH: "${{ env.BACKEND_DIR }}/include"
          LIBRARY_PATH: "${{ env.BACKEND_DIR }}/lib"
        run: python setup.py --with-coverage build_ext --inplace

      - name: Check typing
        run: mypy .
